DROP TABLE IF EXISTS  NC_Accidents_2021;

CREATE TABLE NC_Accidents_2021 (
	ST_CASE integer NOT NULL, 
	STATENAME VARCHAR(35),
	COUNTYNAME VARCHAR(35) NOT NULL,
	CITYNAME VARCHAR(35),
	PEDS Integer NOT NULL,
	FATALS Integer NOT NULL,
	Date DATE,
	LATITUDE FLOAT,
	LONGITUD FLOAT
);

SELECT * FROM NC_Accidents_2021;