CREATE TABLE accidents2021 (
    State_Code INT NOT NULL,
	State VARCHAR (30) NOT NULL,
	Case_Number INT NOT NULL,
	County_Code INT NOT NULL,
	County VARCHAR (30) NOT NULL,
	Monthid INT NOT NULL,
	Month VARCHAR (25) NOT NULL,
	Day INT NOT NULL,
	Day_of_Month INT NOT NULL,
	Day_of_Week INT NOT NULL,
	Weekday VARCHAR (20) NOT NULL,
	Year INT NOT NULL,
	Hour INT NOT NULL,
	Hour_Range VARCHAR (50) NOT NULL,
	Minute INT NOT NULL,
	Minute_Digit INT NOT NULL,
	Latitude FLOAT NOT NULL,
	Latitudeinfo VARCHAR (50) NOT NULL,
	Longitude FLOAT NOT NULL,
	Longitudeinfo VARCHAR (50) NOT NULL,
	Light_Conditionid INT NOT NULL,
	Light_Condition VARCHAR (50) NOT NULL,
	Weatherid INT NOT NULL,
	Weather_Condition VARCHAR (50) NOT NULL,
	Number_of_Deaths INT NOT NULL,
	Start_Hour VARCHAR (10) NOT NULL,
	End_Hour VARCHAR (10) NOT NULL,
    PRIMARY KEY (Case_Number)
	);


CREATE TABLE accidents2020 (
    State_Code INT NOT NULL,
	State VARCHAR (30) NOT NULL,
	Case_Number INT NOT NULL,
	County_Code INT NOT NULL,
	County VARCHAR (30) NOT NULL,
	Monthid INT NOT NULL,
	Month VARCHAR (25) NOT NULL,
	Day INT NOT NULL,
	Day_of_Month INT NOT NULL,
	Day_of_Week INT NOT NULL,
	Weekday VARCHAR (20) NOT NULL,
	Year INT NOT NULL,
	Hour INT NOT NULL,
	Hour_Range VARCHAR (50) NOT NULL,
	Minute INT NOT NULL,
	Minute_Digit INT NOT NULL,
	Latitude FLOAT NOT NULL,
	Latitudeinfo VARCHAR (50) NOT NULL,
	Longitude FLOAT NOT NULL,
	Longitudeinfo VARCHAR (50) NOT NULL,
	Light_Conditionid INT NOT NULL,
	Light_Condition VARCHAR (50) NOT NULL,
	Weatherid INT NOT NULL,
	Weather_Condition VARCHAR (50) NOT NULL,
	Number_of_Deaths INT NOT NULL,
	Start_Hour VARCHAR (10) NOT NULL,
	End_Hour VARCHAR (10) NOT NULL,
    PRIMARY KEY (Case_Number)
	);



CREATE TABLE accidents2019 (
    State_Code INT NOT NULL,
	State VARCHAR (30) NOT NULL,
	Case_Number INT NOT NULL,
	County_Code INT NOT NULL,
	County VARCHAR (30) NOT NULL,
	Monthid INT NOT NULL,
	Month VARCHAR (25) NOT NULL,
	Day INT NOT NULL,
	Day_of_Month INT NOT NULL,
	Day_of_Week INT NOT NULL,
	Weekday VARCHAR (20) NOT NULL,
	Year INT NOT NULL,
	Hour INT NOT NULL,
	Hour_Range VARCHAR (50) NOT NULL,
	Minute INT NOT NULL,
	Minute_Digit INT NOT NULL,
	Latitude FLOAT NOT NULL,
	Latitudeinfo VARCHAR (50) NOT NULL,
	Longitude FLOAT NOT NULL,
	Longitudeinfo VARCHAR (50) NOT NULL,
	Light_Conditionid INT NOT NULL,
	Light_Condition VARCHAR (50) NOT NULL,
	Weatherid INT NOT NULL,
	Weather_Condition VARCHAR (50) NOT NULL,
	Number_of_Deaths INT NOT NULL,
	Start_Hour VARCHAR (10) NOT NULL,
	End_Hour VARCHAR (10) NOT NULL,
    PRIMARY KEY (Case_Number)
	);
	
